#name: CI/CD Pipeline

#on:
#  push:
#    branches: [ "main" ]
#
#jobs:
# build-test-push:
#   runs-on: ubuntu-latest
#
#   env:
#     PYTHONPATH: ${{ github.workspace }}
#
#   steps:
#     - name: Checkout
#       uses: actions/checkout@v4
#
#     - name: Set up Python
#       uses: actions/setup-python@v5
#       with:
#         python-version: "3.11"
#
#     - name: Install dependencies
#        run: |
#         pip install -r requirements.txt
#
#     - name: Lint
#       run: |
#         flake8 .
#
#     - name: Run Tests
#       run: |
#         pytest
#
#     - name: Build Docker image
#       run: |
#         docker build -t ${{ secrets.DOCKER_USERNAME }}/docker-spark-airflow:latest .
#
#     - name: Login to Docker Hub
#       run: |
#         echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
#
#     - name: Push Docker image
#       run: |
#         docker push ${{ secrets.DOCKER_USERNAME }}/docker-spark-airflow:latest

name: Spark Airflow CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-push-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Custom Spark Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/custom-spark:latest .

      - name: Push Spark Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/custom-spark:latest

      - name: Run Docker Compose
        run: |
          docker compose up -d

      - name: Wait for Containers
        run: sleep 20

      - name: Verify Containers
        run: docker ps

      - name: Stop Containers
        run: docker compose down


